### ISSUE TITLE
unable to select a specific name for the environment.

### ISSUE THREAD

**Issue by carcalacus** [layershift/jps_redis_cluster#1]
when deploying from https://raw.githubusercontent.com/layershift/jps_redis_cluster/main/redis_cluster.jps
I tried to rename the environment redis_cluster_msn . It failed with error:
If i deploy using the prposed environment name it works fine

`{"result":2316,"envGroups":[],"nodesInternalDomains":[],"methodName":"createEnv","action":"install","source":"JEL","error":"Invalid domain [redis_cluster_msn ].","nodesData":[],"params":{"settings":{"sslstate":false},"session":"82fdx9c2bdb66fd602fe646b8ba8c1fa5e86b","appid":"1dd8d191d38fff45e62564fcf67fdcd6","domain":"redis_cluster_msn","actionkey":"1631709566754;installapp;;Redis_cluster;-;install;1631709566750;;;;false|a281db1f-c8d9-4b00-91b8-ea20dc9668b4","client_source":null,"ownerUid":"33533","hardwareNodeGroup":"hng-1-vz7","clearUnknown":true},"__info":{"params":{"settings":"{\"mode\":\"newEnv\",\"envName\":\"redis_cluster_msn\",\"region\":\"hng-1-vz7\",\"master\":3,\"cldts\":10}","actionkey":"1631709566754;installapp;;Redis_cluster;-;install;1631709566750;;;;false","jps":"https://raw.githubusercontent.com/layershift/jps_redis_cluster/main/redis_cluster.jps","charset":"UTF-8","hx_lang":"en","session":"82fdxe293b81b1d631db272995a8c4394ea13","ruk":"38a42f54-2399-48d2-8983-dummy-jelastic-dashboard","debug":{"startTime":1631709566764,"duration":7959,"headers":{"x-xss-protection":"1; mode=block","x-resolver-ip":"109.109.136.64","x-content-type-options":"nosniff","server":"openresty","pragma":"no-cache","expires":"Wed, 15 Sep 2021 12:39:33 GMT","date":"Wed, 15 Sep 2021 12:39:34 GMT","content-language":"en-US","cache-control":"no-cache","access-control-allow-origin":"*"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36","cookieEnabled":true,"browserLang":"en-US","timezoneOffset":-180,"tabId":"dummy-jelastic-dashboard","requestCount":90,"initiator":"Error\n    at constructor.onBeforeRequest (https://app.j.layershift.co.uk/optimum/js/e99c3f049dec8cf03de533514614f100.out.js:1612:63823)\n    at h.Event.fire (https://app.j.layershift.co.uk/optimum/js/e99c3f049dec8cf03de533514614f100.out.js:1604:21739)\n    at constructor.fireEvent (https://app.j.layershift.co.uk/optimum/js/e99c3f049dec8cf03de533514614f100.out.js:14:687)\n    at constructor.request (https://app.j.layershift.co.uk/optimum/js/e99c3f049dec8cf03de533514614f100.out.js:1602:22286)\n   ...","app":{"host":"app.j.layershift.co.uk","lang":"en","locale":"en-gb","version":"5.9.7"},"user":{"uid":33533,"status":1,"group":"internal"},"method":"POST","retriesCount":0,"requestId":78,"httpStatus":200,"statusText":"n/a","responseText":"{\"result\":2316,\"response\":{\"result\":2316,\"envGroups\":[],\"nodesInternalDomains\":[],\"methodName\":\"createEnv\",\"action\":\"install\",\"source\":\"JEL\",\"error\":\"Invalid domain [redis_cluster_msn ].\",\"nodesData\":[],\"params\":{\"settings\":{\"sslstate\":false},\"session\":\"82fdx9c2bdb66fd602fe646b8ba8c1fa5e86b\",\"appid\":\"1dd8d191d38fff45e62564fcf67fdcd6\",\"domain\":\"redis_cluster_msn\",\"actionkey\":\"1631709566754;installapp;;Redis_cluster;-;install;1631709566750;;;;false|a281db1f-c8d9-4b00-91b8-ea20dc9668b4\",\"client_source\":null,\"ownerUid\":\"33533\",\"hardwareNodeGroup\":\"hng-1-vz7\"}},\"action\":\"install\",\"source\":\"JEL\",\"error\":\"Invalid domain [redis_cluster_msn ].\"}","aborted":false,"timedout":false}},"url":"/JElastic/marketplace/jps/rest/install","startTime":1631709566764,"duration":7959,"headers":{"x-xss-protection":"1; mode=block","x-resolver-ip":"109.109.136.64","x-content-type-options":"nosniff","server":"openresty","pragma":"no-cache","expires":"Wed, 15 Sep 2021 12:39:33 GMT","date":"Wed, 15 Sep 2021 12:39:34 GMT","content-language":"en-US","cache-control":"no-cache","access-control-allow-origin":"*"}}}`

**Comment by carcalacus** [comment]
it's the "_" underscore in the host name. You cant't have this host name redis_cluster_msn
